const DEFAULT_PORT = 3000 || process.env.PORT;

const DEFAULT_HEADER_CONTENT = { "Content-Type": "application/json" };

const OK_HEADER_CODE = 200;
const NO_CONTENT_HEADER_CODE = 204;
const PARTIAL_HEADER_CODE = 206;
const NOT_FOUND_HEADER_CODE = 404;
const RANGE_NOT_SATISFIABLE_CODE = 416;
const ERROR_HEADER_CODE = 500;

export {
  DEFAULT_PORT,
  DEFAULT_HEADER_CONTENT,
  OK_HEADER_CODE,
  NO_CONTENT_HEADER_CODE,
  PARTIAL_HEADER_CODE,
  NOT_FOUND_HEADER_CODE,
  RANGE_NOT_SATISFIABLE_CODE,
  ERROR_HEADER_CODE,
};
